<?php
/**
 * Opt-in response-header hardening for requests generated by WordPress.
 *
 * Existing headers are never replaced. Web-server, page-cache and CDN responses
 * may bypass WordPress, so the portal's external scan remains the source of truth.
 * HSTS and CSP are deliberately not set here: both need site/host-specific review.
 */

if (!defined('ABSPATH')) {
    exit;
}

class ErrorVault_Security_Hardening {

    const DEFAULT_PERMISSIONS_POLICY = 'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()';

    public static function init() {
        add_filter('wp_headers', array(__CLASS__, 'filter_headers'), 100);
        add_action('send_headers', array(__CLASS__, 'send_headers'), 100);
        add_action('login_init', array(__CLASS__, 'send_headers'), 100);
        add_action('admin_init', array(__CLASS__, 'send_headers'), 100);

        // Run once early as well, so PHP's own header is removed before a response
        // takes a path that does not invoke WordPress's normal header hooks.
        self::remove_powered_by(self::settings());
    }

    /**
     * Add enabled headers to WordPress's normal response map without replacing
     * headers supplied by the host, another plugin or WordPress itself.
     */
    public static function filter_headers($headers) {
        $headers = is_array($headers) ? $headers : array();
        $settings = self::settings();

        if (!empty($settings['security_remove_powered_by'])) {
            foreach (array_keys($headers) as $name) {
                if (0 === strcasecmp((string) $name, 'X-Powered-By')) {
                    unset($headers[$name]);
                }
            }
        }

        foreach (self::configured_headers($settings) as $name => $value) {
            if (!self::array_has_header($headers, $name)) {
                $headers[$name] = $value;
            }
        }

        return $headers;
    }

    /**
     * Cover wp-login.php, wp-admin and unusual WordPress response paths that do
     * not consume the wp_headers filter. Existing queued PHP headers win.
     */
    public static function send_headers() {
        if (headers_sent()) {
            return;
        }

        $settings = self::settings();
        self::remove_powered_by($settings);

        foreach (self::configured_headers($settings) as $name => $value) {
            if (!self::response_has_header($name)) {
                header($name . ': ' . $value, true);
            }
        }
    }

    /**
     * Return only the explicitly enabled, low-risk headers.
     */
    public static function configured_headers($settings) {
        $settings = is_array($settings) ? $settings : array();
        $headers = array();

        if (!empty($settings['security_header_nosniff'])) {
            $headers['X-Content-Type-Options'] = 'nosniff';
        }
        if (!empty($settings['security_header_referrer_policy'])) {
            $headers['Referrer-Policy'] = 'strict-origin-when-cross-origin';
        }
        if (!empty($settings['security_header_frame_options'])) {
            $headers['X-Frame-Options'] = 'SAMEORIGIN';
        }
        if (!empty($settings['security_header_permissions_policy'])) {
            $policy = self::sanitize_permissions_policy(isset($settings['security_permissions_policy']) ? $settings['security_permissions_policy'] : '');
            $headers['Permissions-Policy'] = '' !== $policy ? $policy : self::DEFAULT_PERMISSIONS_POLICY;
        }

        return $headers;
    }

    /**
     * A header value must never contain control characters. Keep printable ASCII
     * only and cap its size; Permissions-Policy directives and origins fit this.
     */
    public static function sanitize_permissions_policy($value) {
        $value = preg_replace('/[^\x20-\x7E]/', ' ', (string) $value);
        $value = preg_replace('/\s+/', ' ', trim($value));
        return substr($value, 0, 1000);
    }

    private static function settings() {
        return get_option('errorvault_settings', array());
    }

    private static function array_has_header(array $headers, $wanted) {
        foreach (array_keys($headers) as $name) {
            if (0 === strcasecmp((string) $name, (string) $wanted)) {
                return true;
            }
        }
        return false;
    }

    private static function response_has_header($wanted) {
        foreach (headers_list() as $line) {
            $name = strstr($line, ':', true);
            if (false !== $name && 0 === strcasecmp(trim($name), (string) $wanted)) {
                return true;
            }
        }
        return false;
    }

    private static function remove_powered_by(array $settings) {
        if (!empty($settings['security_remove_powered_by']) && !headers_sent()) {
            header_remove('X-Powered-By');
        }
    }
}
